config/routes.rb
Rails.application.routes.draw do
    resources :services do
        
        resources :api_specs do
            member do
                get 'show_swagger', to: 'api_specs#show_swagger'
            end
        end
    end

    get 'overview_dashboard', to: 'dashboards#overview'
    get 'schemas', to: 'schemas#index'
    get 'purposes', to: 'dashboards#purposes'
    get 'network', to: 'dashboards#network'
    get 'utilizer', to: 'utilizers#index'
    get 'schemas/:name/raw_data', to: 'schemas#get_raw_schema_by_name', as: 'schema_spec'
    get 'purposes/:name/raw_data', to: 'schemas#get_purpose_ref_by_names', as: 'purpose_spec'

    root 'services#index'

    scope "/api" do
        scope "v1" do
            scope "/services" do
                post 'update_service' => 'gitlab_repos#update'
                get 'hello' => 'gitlab_repos#hello'
            end
        end

    end
end

app/models/service.rb
class Service < ApplicationRecord
    # belongs_to :service_provider
    has_many :api_specs

    has_many :service_connections
    has_many :senders, through: :service_connections

    has_many :receiving_connections, foreign_key: :sender_id, class_name: "ServiceConnection"
    has_many :receivers, through: :receiving_connections, source: :service

    def transparency_service
        Tira::OpenApiServices::OpenApi3ServiceService.new(self)
    end

    def get_spec
        if api_spec = self.api_specs.last
            return api_spec.get_specification_file_content
        end
        return nil
    end

    def api_spec
        self.api_specs.last
    end

    def repo_directory
        Rails.root + 'data/git_repos/' + self.name
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    # leave out ignore ones
    services = Service.all.where(ignore: [nil, false])
    if request.params[:ignored]
      @services = Service.all.where.not(ignore: [nil, false])
    else
      @internal_services = services.where(internal: true)
      @external_services = services.where(internal: false)
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :gitlab_repo, :internal, :ignore, :service_provider_id, sender_ids: [], receiver_ids: [])
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_edit_form.erb
<%= simple_form_for(@service, html: { class: 'form-horizontal' }) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-4">
      Service:
    </div>
    <div class="col-6">
       <strong><%= service.name %></strong>
    </div>  
  </div>

  <div class="row">
    <div class="col-4">
      Internal Service
    </div>
    <div class="col-6">
      <%= form.check_box :internal %>
    </div>  
  </div>
  <div class="row">
    <div class="col-4">
      Service does not process personal data
    </div>
    <div class="col-6">
      <%= form.check_box :ignore %>
    </div>  
  </div>
  <div class="row">
    <div class="col-6">
      <br>
      <h4>Senders</h4>
      <%= form.select :sender_ids, Service.all.where(ignore: [nil, false]).where.not(id: service.id).collect {|x| [x.name, x.id]}, {}, :multiple => true, class: 'multipleSelect' %>  
    </div>
    <div class="col-6">
      <br>
      <h4>Receivers</h4>
      <%= form.select :receiver_ids, Service.all.where(ignore: [nil, false]).where.not(id: service.id).collect {|x| [x.name, x.id]}, {}, :multiple => true, class: 'multipleSelect' %>  
    </div>
  </div>

  

  <div class="field">
    
  </div>

  <div class="actions">
    <%= form.submit 'Save Service', :class => 'btn btn-large btn-main' %>
  </div>
<% end %>



<%#= javascript_include_tag "popper" %>
<%= javascript_include_tag "jquery-multi-select" %>
<script type="text/javascript">
  $('.multipleSelect').multiSelect()
</script>

app/views/services/_new_form.html.erb
<%= simple_form_for(@service, html: { class: 'form-horizontal' }) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gitlab_repo_url %>
    <%= form.text_field :gitlab_repo_url %>
  </div>

  <div class="field">
    <%= form.label :internal %>
    <%= form.check_box :internal %>
  </div>

  <div class="field">
    <%= form.label :service_provider_id %>
    <%= form.number_field :service_provider_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_services.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Spec Status</th>
      <th>Service provider</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% services.each do |service| %>
      <tr 
        <% if service.ignore %>
          class="inactive"
        <% end %>
      >
        <td><%= link_to service.name, service_api_specs_path(service) %></td>
        <td>
          <% if service.api_specs.count > 0 %>
            <span class="badge success"> Spec present </span>
          <% else %>
            <span class="badge error"> No spec found </span>
          <% end %>
        </td>
        <td><%= service.service_provider_id %></td>
        <td>
          <%= link_to edit_service_path(service) do %>
            <i class="fa fa-pencil-square-o"></i>
          <% end %>
          &nbsp;
          <% if service.git_http_url %>
            <a href="<%= service.git_http_url %>" target="_blank">
              <i class="fa fa-external-link"></i>
            </a>
          <% end %>
          &nbsp;
          <%= link_to service, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i style="" class="fa fa-times red-text"></i>
          <% end %>
          &nbsp;
          <% if service.api_specs.last %>
            <%= link_to 'Show Spec', show_swagger_service_api_spec_path(service, service.api_specs.last) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'edit_form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Services</h1>

<% if not request.params[:ignored] %>
    <h2>Internal</h2>
    <%= render 'services', services: @internal_services %>
    <hr>
    <%= link_to 'New Service', new_service_path, class: 'btn btn-main' %>
    <%= link_to 'Further Services without Personal Data', services_path(ignored: 'true'), class: 'btn btn-default' %>
    <hr>
    <h2>External</h2>
    <%= render 'services', services: @external_services %>
<% else %>
<%= link_to 'All Services', services_path, class: 'btn btn-default' %>
    <h2>Services that do not process personal data</h2>
    <p class="subheading">
        Services, that were registered, as they are versioned using git but that are not involved in the processing of personal data
    </p>
    <%= render 'services', services: @services %>

<% end %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'new_form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Gitlab repo:</strong>
  <%= @service.gitlab_repo_url %>
</p>


<p>
  <strong>Internal:</strong>
  <%= @service.internal %>
</p>

<p>
  <strong>Service provider:</strong>
  <%= @service.service_provider_id %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>