config/routes.rb
Rails.application.routes.draw do
    resources :services do
        
        resources :api_specs do
            member do
                get 'show_swagger', to: 'api_specs#show_swagger'
            end
        end
    end

    get 'overview_dashboard', to: 'dashboards#overview'
    get 'schemas', to: 'schemas#index'
    get 'purposes', to: 'dashboards#purposes'
    get 'network', to: 'dashboards#network'
    get 'utilizer', to: 'utilizers#index'
    get 'schemas/:name/raw_data', to: 'schemas#get_raw_schema_by_name', as: 'schema_spec'
    get 'purposes/:name/raw_data', to: 'schemas#get_purpose_ref_by_names', as: 'purpose_spec'

    root 'services#index'

    scope "/api" do
        scope "v1" do
            scope "/services" do
                post 'update_service' => 'gitlab_repos#update'
                get 'hello' => 'gitlab_repos#hello'
            end
        end

    end
end

app/models/utilizer.rb
class Utilizer < ApplicationRecord
end

app/controllers/utilizers_controller.rb
class UtilizersController < ApplicationController

    def index
        @utilizers = transparency_service.get_all_utilizer(including_categories: true, including_services: false)

    end


    private
    def transparency_service
        Tira::OpenApiServices::OpenApi3SystemService.new()
    end
end

app/helpers/utilizers_helper.rb
module UtilizersHelper
end

app/views/utilizers/edit.html.erb
<%= simple_form_for(@api_spec, url: utilizers_path(@utilizer), method: :post, html: { class: 'form-horizontal' }) do |form| %>

  <div class="field">
    <%= form.input :parent_utilizer %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/utilizers/index.html.erb
<h1>Utilizers</h1>

<p class="info-cite">
    <span class="fa fa-info"></span>
    Utilizers & Utilizer Categories only come from exposed data. Service Processors (like AWS) apply for all data.
</p>

<table class="table table-striped bigger-table">
    <thead>
        <tr>
            <th style="text-align: center;">Name</th>
            <th>Type</th>
            <th>Personal Data</th>
            <th>Services</th>
            <th>Third Country</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @utilizers.each do |utilizer, personal_data| %>
            <tr>
                <td class="main-td"><%= utilizer.name %></td>
                <td>
                    <% if utilizer.class == Tira::Property::UtilizerCategory %>
                        Utilizer Category
                    <% else %>
                        Utilizer
                        <% if utilizer.service_wide %>
                            (Service Processor)
                        <% end %>
                    <% end %>
                </td>
                <td>
                    <ul>
                        <% personal_data.each do |pd| %>
                          <li><%= pd.name %></li>  
                        <% end %>
                    </ul>
                </td>
                <td>
                    <ul>
                        <% personal_data.map{|pd| pd.service}.uniq.each do |service| %>
                            <li><%= service.name %></li>
                        <% end %>
                    </ul>


                </td>
                <td>
                    <% if utilizer.non_eu? %>
                        <span class="alert-color">Yes</span>
                        <% if country = utilizer.country %>
                            <span class="gray-text">
                                -&nbsp;<%= country %>
                            </span>
                        <% end %>
                    <% else %>
                        <span class="sucess-color">No</span>
                    <% end %>   
                            
                </td>
                <td></td>
            </tr>
        <% end %>
    </tbody>
</table>