config/routes.rb
Rails.application.routes.draw do
    resources :services do
        
        resources :api_specs do
            member do
                get 'show_swagger', to: 'api_specs#show_swagger'
            end
        end
    end

    get 'overview_dashboard', to: 'dashboards#overview'
    get 'schemas', to: 'schemas#index'
    get 'purposes', to: 'dashboards#purposes'
    get 'network', to: 'dashboards#network'
    get 'utilizer', to: 'utilizers#index'
    get 'schemas/:name/raw_data', to: 'schemas#get_raw_schema_by_name', as: 'schema_spec'
    get 'purposes/:name/raw_data', to: 'schemas#get_purpose_ref_by_names', as: 'purpose_spec'

    root 'services#index'

    scope "/api" do
        scope "v1" do
            scope "/services" do
                post 'update_service' => 'gitlab_repos#update'
                get 'hello' => 'gitlab_repos#hello'
            end
        end

    end
end

app/models/api_spec.rb
class ApiSpec < ApplicationRecord
    belongs_to :service

    has_one_attached :open_api_specification

    # validates :spec, presence: true


    def get_personal_data
        # @spec_service.get_schemas_from_path
        transparency_service.consumed_personal_data
    end

    def transparency_service
        Tira::OpenApiServices::OpenApi3DocumentService.new(self.get_specification_file_content, self.service) if self.get_specification_file_content and self.service
    end

    def get_specification_file_content
        if self.open_api_specification
            file = File.open(ActiveStorage::Blob.service.send(:path_for, self.open_api_specification.key))
            data = File.read(file)
            case self.open_api_specification.content_type
                when "application/x-yaml"
                    return YAML.load(data).to_json
                when "application/json"
                    # ##############################
                    # TODO Validate JSON
                    # 
                    # (probably at another place (on upload), but has to be done before here)
                    # ##############################
                    
                    # json data can be utilized as is
                    return data
            else
                return nil
            end
        end
        return nil
    end

end

app/controllers/api_specs_controller.rb
class ApiSpecsController < ApplicationController
    before_action :set_service
    before_action :set_api_spec, only: [:show_swagger]

    def index
        @api_specs = @service.api_specs.order(created_at: :desc)
    end

    def new
        @api_spec = ApiSpec.new(service: @service)
    end


    def show_swagger
        @personal_data = @api_spec.get_personal_data

        @spec = @api_spec.get_specification_file_content
        @spec_service = @api_spec.transparency_service
        # @spec_service.get_schemas_from_path

    end

    def create
        @api_spec = ApiSpec.new(api_spec_params)
        @api_spec.service = @service

        respond_to do |format|
            if @api_spec.save
                format.html { redirect_to service_api_specs_path(@service), notice: 'Spec successfully created.' }
            else
                format.html { render :new }
                format.json { render json: @api_spec.errors, status: :unprocessable_entity }
            end
        end
    end

    private

    def set_api_spec
      @api_spec = ApiSpec.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    def api_spec_params
      params.require(:api_spec).permit(:spec, :description, :commit_message, :branch, :author, :commit_url)
    end
end

app/helpers/api_specs_helper.rb
module ApiSpecsHelper
end

app/views/api_specs/_api_spec.html.erb
<tr>
    <td><%= api_spec.description %></td>
    <td><%= I18n.l api_spec.created_at, :format => :short  %></td>
    <td>
        <%= api_spec.commit_message %>
        <% if api_spec.commit_url %>
            &nbsp;
            <a href="<%= api_spec.commit_url %>" target="_blank">
                <span class="fa fa-external-link"></span>
            </a>
        <% end %>
    </td>
    <td><%= api_spec.branch %></td>
    <td><%= api_spec.author %></td>
    <td>
        <% if api_spec.open_api_specification.attached?  %>
            <%= link_to 'View Spec', show_swagger_service_api_spec_path(api_spec.service, api_spec) %>&nbsp;
            <a href="<%= url_for(api_spec.open_api_specification) %>"><span class="fa fa-download"></span></a>
        <% end %>
    </td>
</tr>

app/views/api_specs/_form.html.erb
<%= simple_form_for(@api_spec, url: service_api_specs_path(@service), method: :post, html: { class: 'form-horizontal' }) do |form| %>


  <div class="field">
    <%= form.input :spec, as: :text %>
  </div>
  <div class="field">
    <%= form.input :description %>
  </div>
  <div class="field">
    <%= form.input :commit_message %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/api_specs/_tira_spec_info.html.erb
<div class="row apispec-info">  
      <div class="col-12">
        <div class="card">
          
          <h4 class="card-header">TransparencyHub Information</h5>
          <div class="card-body">
            <!-- <h4 class="card-title">General Info</h5> -->
              <% if not @spec_service.valid? %>
                <h6 class="card-text alert-text">
                  <span class="fa fa-exclamation-circle"></span> Spec not valid
                  <ul>
                    <% @spec_service.errors.each do |error| %>
                      <li><%= error %></li>
                    <% end %>
                  </ul>
                </h6>
              <% else %>
                <h6 class="card-tex success-text">
                  <span class="fa fa-check-circle"></span> Spec valid
                </h6>
                <hr>
                <h4>Personal Data within this Spec</h4>
                  
                <% @personal_data.each do |schema_name, personal_datum| %>
                  <div class="row">
                    <div class="col-12">

                      <h5><%= schema_name %></h5>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-3">
                      <h6>Properties</h6>
                      <ul>
                        <% personal_datum.property_schemas.each do |property_schema| %>
                        <!-- property has only one key -->
                          <li>
                            <%= property_schema.name %>
                            <% if property_schema.property_schemas.size > 0 %>
                              <ul>
                                <% property_schema.property_schemas.each do |ps| %>
                                  <li><%= ps.get_name %></li>
                                <% end %>
                              </ul>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                    <% if personal_datum.retention_time %>
                      <div class="col-md-3">
                        <h6>Retention Time</h6>
                        <p><%= personal_datum.retention_time.retention_timespan %> days</p>
                      </div>
                    <% end %>
                    <% if personal_datum.purposes and personal_datum.purposes.get_permitted_purposes %>
                      <div class="col-md-3">
                        <h6>Purposes</h6>
                        <ul>
                          <% personal_datum.purposes.get_permitted_purposes.each do |purpose| %>
                          <li><%= purpose %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>
                  </div>

                <% end %>


              <% end %>
          </div>
        </div>
      </div> 
    </div>

app/views/api_specs/index.html.erb
<h1>API Specs of <i><%= @service.name %></i></h1>

<%= link_to 'New Spec', new_service_api_spec_path(@service), class: 'btn btn-main' %>


<table class="table table-striped">
    <thead>
        <tr>
            <th>Description</th>
            <th>Datetime</th>
            <th>Commit Message</th>
            <th>Branch</th>
            <th>Author</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render @api_specs %>
    </tbody>
</table>

app/views/api_specs/new.html.erb
<h1>New API-Spec for <%= @service.name %></h1>

<%= render 'form' %>

app/views/api_specs/show_swagger.html.erb
  <!-- <head> -->
    <!-- <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="./swagger-ui.css" >
    <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" /> -->
  <!-- </head> -->

  <div class="thub-swagger-container">
    <div class="thub-spec-header row">
      <div class="col-12">
        <h1 class="">Api Spec of Service <i><%= @service.name %></i></h1>
          <p>Commit: <%= @api_spec.commit_message %><br>
          Date: <%= I18n.l @api_spec.created_at, :format => :short  %><br>
          Author: <%= @api_spec.author %></p>
        
        <% if @api_spec.open_api_specification.attached?  %>
          <%= link_to '<span class="fa fa-download"></span> Download'.html_safe, url_for(@api_spec.open_api_specification), class: 'btn btn-main' %>

        <% end %>



        <%= link_to 'All Specs of Service', service_api_specs_path(@service), class: 'btn btn-default' %>
        <%= link_to 'All Services', services_path, class: 'btn btn-default' %>
      </div>
    </div>

    <%= render 'tira_spec_info' %>

    <div id="swagger-ui">
      <% if not @spec %>
        <p class="error">There seems to be an Error within this spec.</p>
      <% end %>
    </div>
  </div>

  <%# 
    approach is to include and serve all relevant swagger ui files ourselves
    this is done by serving the swagger-ui-dist directory via the rails asset pipeline 
  %>

<% if @spec %>
  <%= javascript_include_tag "swagger/swagger-ui-bundle" %>
  <%= javascript_include_tag "swagger/swagger-ui-standalone-preset" %>
  <%= stylesheet_link_tag "swagger/swagger-ui" %>
  <script>
  window.onload = function() {
    // Begin Swagger UI call region
    const ui = SwaggerUIBundle({
      // url: "https://petstore.swagger.io/v2/swagger.json",
      spec: <%= @spec.html_safe %>,
      dom_id: '#swagger-ui',
      deepLinking: true,
      showExtensions: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    })
    // End Swagger UI call region

    window.ui = ui
  }
</script>
<% end %>