config/routes.rb
Rails.application.routes.draw do
    resources :services do
        
        resources :api_specs do
            member do
                get 'show_swagger', to: 'api_specs#show_swagger'
            end
        end
    end

    get 'overview_dashboard', to: 'dashboards#overview'
    get 'schemas', to: 'schemas#index'
    get 'purposes', to: 'dashboards#purposes'
    get 'network', to: 'dashboards#network'
    get 'utilizer', to: 'utilizers#index'
    get 'schemas/:name/raw_data', to: 'schemas#get_raw_schema_by_name', as: 'schema_spec'
    get 'purposes/:name/raw_data', to: 'schemas#get_purpose_ref_by_names', as: 'purpose_spec'

    root 'services#index'

    scope "/api" do
        scope "v1" do
            scope "/services" do
                post 'update_service' => 'gitlab_repos#update'
                get 'hello' => 'gitlab_repos#hello'
            end
        end

    end
end

app/views/layouts/_flashs.html.erb
<%# flash_types: :error, :success, :warning, :info] %>


<div class="container flash-container" >
 <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "container flash-message #{key}") %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <a class="navbar-brand" href="/">TransparencyHub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="<%= url_for services_path %>">Services</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="<%= url_for overview_dashboard_path %>">Schemas</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="<%= url_for purposes_path %>">Purposes</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="<%= url_for utilizer_path %>">Utilizers</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Dashboards

          </a>
          <div class="dropdown-menu">
              <%#= link_to 'Overview', overview_dashboard_path, class: "dropdown-item" %>
              <%= link_to 'Network', network_path, class: "dropdown-item" %>
              <%#= link_to '<i class="fa fa-sign-out"></i> &nbsp;Ausloggen'.html_safe, destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
          </div>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-cogs"></span>&nbsp;Actions
          </a>
          <div class="dropdown-menu">
              <%#= link_to '<i class="fa fa-lock"></i> &nbsp;&nbsp;Passwort ändern'.html_safe, edit_user_registration_path, class: "dropdown-item" %>
              <%#= link_to '<i class="fa fa-sign-out"></i> &nbsp;Ausloggen'.html_safe, destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
          </div>
      </li>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) + " | TransparencyHub" : "TransparencyHub" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container nav-container">
      <!-- nav -->
      <%= render 'layouts/navbar' %>
    </div>


    <%= render 'layouts/flashs' if !flash.empty? %>



    <div class="container header-container">
      <!-- header -->
      <!-- filterin oder sowas -->
    </div>

    <div class="container content-container">
      <!-- content -->
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </body>
</html>